### ISSUE TITLE
Cannot execute binary file

### ISSUE THREAD

**Issue by recursivecodes** [devsoap/fn-gradle-plugin#12]
Does this plugin work on Mac?

When I run the fnDeploy task, I receive: `build/fn/fn_linux: cannot execute binary file` which seems to imply that it assumes I'm running on Linux.

**Comment by johndevs** [comment]
Looks like there was a bug in the OS check as Mac is a Unix variant as well :)

Thanks for reporting the issue :+1:

**Comment by recursivecodes** [comment]
Yep, exactly.  Seems like you could put the Mac check first, then the Linux check in the else if, since Mac returns true for Os.FAMILY_UNIX.

https://github.com/devsoap/fn-gradle-plugin/blob/c510ac0d75db67e95f12ddd0afaa410df3b95fba/src/main/groovy/com/devsoap/fn/tasks/FnInstallCliTask.groovy#L61

**Comment by johndevs** [comment]
Just released a new version with this fix, please try 0.1.7 and see if it now works better.
